version: '3.7'

services:
  postgresql:
    image: bitnami/postgresql:12
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_DATABASE=sonar
      - POSTGRESQL_USERNAME=sonar
      - POSTGRESQL_PASSWORD=sonar12345
    volumes:
      - postgresql_data:/bitnami/postgresql
  sonarqube:
    image: bitnami/sonarqube:8
    ports:
      - '9000:9000'
    environment:
      - SONARQUBE_DATABASE_NAME=sonar
      - SONARQUBE_DATABASE_USER=sonar
      - SONARQUBE_DATABASE_PASSWORD=sonar12345
    volumes:
      - sonarqube_data:/bitnami

volumes:
  sonarqube_data:
  postgresql_data: